### ISSUE TITLE
Add parameter timeref to MCTopicRequest

### ISSUE THREAD

**Issue by migmam** [MeaningCloud/meaningcloud-php#3]
Hi!!

How can I add the parameter timeref in MCTopicRequest class calling the constructor?

Need something like
$this->addParam('timeref', '2022-03-08 00:00:00');

**Comment by sandra25lopez** [comment]
Hi Miguel!

You can use the otherParams parameter in the construct. Something like:


     new MCTopicsRequest($key, $lang, $txt="", $url="", $doc="", $topicType="a", ["timeref" => "2022-03-08"]...)

Regards,

**Comment by migmam** [comment]
Perfect!!

Gracias!

**Comment by migmam** [comment]
Hola Sandra. ¿Hay alguna forma de filtrar para que no te salgan resultados de nombre de personas "famosas"?. P.e. Si hago una búsqueda por "Hola me llamo Cristina", la entidad Cristina me la devuelve cómo 1. Nombre de un pueblo y 2. como "Cristina Cifuentes" pero no simplemente como una entidad nombre "Cristina".
