### ISSUE TITLE
Entity FullName

### ISSUE THREAD

**Issue by migmam** [MeaningCloud/meaningcloud-php#4]
Hola Sandra. ¿Hay alguna forma de filtrar para que no te salgan resultados de nombre de personas "famosas"?. P.e. Si hago una búsqueda por "Hola me llamo Cristina", la entidad Cristina me la devuelve cómo 1. Nombre de un pueblo y 2. como "Cristina Cifuentes" pero no simplemente como una entidad nombre "Cristina".

**Comment by joelpoc** [comment]
Hola! Parece que el problema está en los recursos léxicos y en cómo se relacionan las entidades: los hemos actualizado y compilado de nuevo. Gracias por tus comentarios! :)

**Comment by migmam** [comment]
Hola @joelpoc. Sigue ocurriendo:

![image](https://user-images.githubusercontent.com/14196643/174474571-54586782-8aa1-47f7-9f20-8e5f211ef0ff.png)

**Comment by migmam** [comment]
Buenas tardes. ¿Alguna novedad sobre la incidencia?
Saludos.

**Comment by joelpoc** [comment]
En breve se subirán todos los cambios a producción. Gracias por tu paciencia.
